project:
  type: website
  output-dir: _site

website:
  title: "Md Ragib Rownak"                    # <-- CHANGE THIS
  description: "PhD Candidate, The Ohio State University" # <-- CHANGE THIS
  site-url: https://rownak01.github.io  # <-- CHANGE THIS

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: posts.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/rownak01  # <-- CHANGE THIS
      - icon: envelope
        href: mailto:rownak.1@osu.edu  # <-- CHANGE THIS

  page-footer:
    center: |
      Built with [Quarto](https://quarto.org/) · © 2025 Md Ragib Rownak

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

execute:
  freeze: auto
